### ISSUE TITLE
Add support to gnome 40

### ISSUE THREAD

**Issue by SandHilt** [Schneegans/Fly-Pie#114]
## The Motivation
Some distro have support to gnome 40.

## The Solution
Add support to gnome 40.

## The Alternatives
Don't add support and some distros deprecated this extension like Dash to Dock.

**Comment by Schneegans** [comment]
It's been ported already, but sadly there's a bug in GTK which renders it more or less unusable currently. Due to the bug, there's no drag and drop in the menu editor (and this is pretty important). Everything else wokls already...

Read more here: #100 

I'll leave this issue open until #100 is merged so that others can read this as well!

**Comment by Schneegans** [comment]
I just released Fly-Pie 7 with support for GNOME Shell 40+. It will take some time until it gets reviewed on extensions.gnome.org. You may either wait or install the extension from the release here on Github!
