### ISSUE TITLE
Support for other WM/DE

### ISSUE THREAD

**Issue by i-need-to-tell-you-something** [Schneegans/Fly-Pie#118]
## The Motivation
People who would want Fly-Pie, but are not on Gnome.

## The Solution
Providing installation instructions and limited support for environments without the Gnome DE. So that I can use some or most of Fly-Pie features on KDE. This might increase the number of support requests even if an appendix were to be added to the readme saying that only Gnome is officially supported.

## The Alternatives
* Potential users switch to Gnome if the pile of awesome software on Gnome grows very large.
* Potential users continue using Gnome-Pie for as long as possible and avoid looking at videos or screenshots of Fly-Pie.
* Fully supporting non-Gnome DE-s.

**Comment by Schneegans** [comment]
Thank you for the request! And yes, this is kind of an obvious thing to come up with and has been requested multiple times already. I've given an answer in #22. More in-depth information can be found [here](http://schneegans.github.io/news/2020/08/13/flypie).

I think that I will leave this issue open, so that others do not need to create similar issues.

If anybody want's to try creating a stand-alone gjs application based on Fly-Pie, I would happily provide support! But the limitations I listed in the linked pages above will be very hard to overcome...

**Comment by i-need-to-tell-you-something** [comment]
Feel free to close it as well. I personally searched the closed issues as well, but I only used the keyword "KDE". :woman_facepalming:. Some people might not find it unless you make this (or #22 ) a pinned issue. Thanks for your attention and the thorough response and the awesome software!

**Comment by Schneegans** [comment]
That's a good idea!
