### ISSUE TITLE
Continue to support translating of version 6

### ISSUE THREAD

**Issue by daPhipz** [Schneegans/Fly-Pie#133]
## The Motivation

Many users are still on GNOME 3.38 or lower, especially on LTS distro releases like Ubuntu 20.04 or 18.04.
I can understand why Fly-Pie is making a hard cut and dropping 3.38 support with version 7, but I think it should still be possible to contribute translations to version 6.

## The Solution

Provide a "legacy" version which includes translation updates from time to time.
However, I don't know if this is possible (1) from Weblate's side (maybe by adding another "component" and telling Weblate to file PRs for this component to a `gnome-3.38` branch in the repo?) and (2) because of the versioning scheme that GNOME uses for extensions. Since it is only one incrementing number and no "point releases" like `6.1` or `6.2`, this may be problematic...

What do you think?

**Comment by Schneegans** [comment]
This is a difficult issue. Very difficult! Here are some solutions I can think of:

## a) Alternating Versions

I talked to the folks behind extensions.gnome.org and they said that it would be ok to use - let's say - odd version numbers for GNOME 3.3x releases and even version numbers for GNOME 40+ releases. We would need to separate branches then. Whether Weblate supports this - I don't know (yet).

## b) A Separate Fly-Pie-Legacy Extension

This could be developed at its own pace. But people would need to switch extensions explicitly to get updates. And it has the same drawbacks as a). 

## c) The REAL Solution

I think the only good solution is to support **all** GNOME versions from **one** code base. Keeping backwards compatibility while porting to GNOME 40 was impossible since _a lot_ of code had to be changed. Nevertheless, backporting Fly-Pie 7 to GNOME 3.3x should be easier, as many changes introduced with GTK4 were backported to GTK3 as well. I could try this, but I may fail... The biggest issue is the settings dialog - the `*.ui` files which have thousands of lines of code will need to exist twice making the maintenance really cumbersome. Yet this back-port can easily require weeks or months of work. Do we want this? In this time I could implement cool new things and eventually people will move on anyways...

But I think from a translator's point of view a) and b) are pretty bad. Does one really want to translate a project _twice_? Also, I do not really want to setup all the comments and screenshots once more :disappointed:

**Comment by daPhipz** [comment]
> odd version numbers for GNOME 3.3x releases and even version numbers for GNOME 40+ releases

So whenever there is an odd number release, GNOME 40+ would just ignore it (because of not being listed as supported in `metadata.json`) and **re-check** for every future release if it is supported again? Good to know!

I can see why you prefer to have only one codebase for all GNOME versions and have only one "hot" development branch.
However, I think it would not be necessary to do any "real" coding work on the legacy branch at all - updating the translations by merging Weblate PRs from time to time would be enough, IMO.

> the `*.ui` files which have thousands of lines of code will need to exist twice making the maintenance really cumbersome.

~Do you know about [`gtk4-builder-tool`](https://developer-old.gnome.org/gtk4/stable/gtk4-builder-tool.html)?~
(I thought this would make it easier to manage `*.ui` files, since it takes GTK3 `ui` files and ports them to GTK4. I've seen it in use at other extensions - but now, actually looking at the docs, they say that the `--3to4` flag is meant only as a starting point when making the step from GTK3 to GTK4 - and I think you are already beyond that.)

> Does one really want to translate a project twice?

That's really up to the translators xD If they want to do the work and contribute to the legacy version, they can - if not, so be it ;)

I would be happy to take responsibility of that legacy branch, if you wanted (since I won't be making the leap to 40+ for some time on my main computer). Be warned, though - apart from bash scripting, Makefiles, translating and its infrastructure, I am not that experienced. Nothing Mr. Google and some time wouldn't fix, though ;)
I am 100% capable of dealing with the work I described above, that's for sure. So, if this is what's holding you back - I am happy to jump in! :rocket:

**Comment by Schneegans** [comment]
Thank you for the support! I think I'll dedicate some time in the coming days to attempt a backport. After some time, I'll be able to estimate the effort. If this was possible, it would be the best solution of all.

**Comment by Schneegans** [comment]
Merged! But feel free to test it on GNOME 3.3x, I only played around in a VM and added some basic test. There will be definitely some bugs hidden... :)
