### ISSUE TITLE
Cinnamon support

### ISSUE THREAD

**Issue by Secret-chest** [Schneegans/Fly-Pie#198]
## The Motivation
Some prefer Cinnamon

## The Solution
Support Cinnamon

## The Alternatives
--

**Comment by Schneegans** [comment]
Thanks for the suggestion! However, given the fact that Cinnamon was forked from GNOME Shell more than ten years ago, I doubt that it would be easy (if possible at all). Instead of porting the extension to each an every desktop environment, it would be better to create a standalone version of Fly-Pie. And then we are at #22.

So I think this will not happen in the near future. If I have _a lot of time_ and if this gets requested by many users, I may consider an attempt. But for now, I do not have enough spare time to do this :wink:

**Comment by Schneegans** [comment]
I just published some [news regarding a platform-agnostic pie menu](https://ko-fi.com/post/Introducing-Ken-Do-L3L7L0FQ2) which I am working on! Once this is working, I will most likely support cinnamon as well. At the end of the post, I wrote down some ways how you could contribute to the project. I would be more than happy if you would follow the progress and support the development along the way :smile:

**Comment by Secret-chest** [comment]
Now, this is nice! I'm really bad at JavaScript, but I'm sure your new menu will be just as good.
