### ISSUE TITLE
Allow to take over already used shortcuts easily

### ISSUE THREAD

**Issue by jle64** [Schneegans/Fly-Pie#238]
## The Motivation

Currently associating a shortcut to a menu isn't possible if the shortcut is already used by something else. For example, trying to set "Super+Space" as a shortcut for a menu doesn't work because Gnome uses it by default as a way to switch input source.

So before you can use it in fly-pie, you have to go into gnome settings, browse all the multiple pages of shortcuts until you find the one that poses problem, then remove it, and then finally you can set it in fly-pie.

## The Solution

It would be cool if fly-pie could just show a prompt like "This shortcut is already used by XXX, do you want to overwrite that ? [Yes/No]".

**Comment by Schneegans** [comment]
Hi there! Thank you for this suggestion! However, I think that this is impossible as Fly-Pie cannot know that the user attempted to press a shortcut which is already bound. These things happen in this case:
* The user clicks on the shortcut-select button
* The user presses "Super+Space" because he wants to bind this combination
* GNOME Shell consumes the key events since they are bound globally
* Fly-Pie does not receive any events and has no idea which buttons were pressed by the user

Or do you have an idea how this could work?

**Comment by jle64** [comment]
Ok, I feared that would be the case, but not being sure I figured I would ask anyway.

> Or do you have an idea how this could work?

The only ideas I have range from non-ideal to ugly hack so I'm going to refrain from suggesting them :upside_down_face: 

Maybe you can still add some warning text like "if your pressed keys aren't detected don't forget to look in settings > keyboard > shortcuts if they're already assigned" ? At first I didn't realise this was the issue so this might already save some time to some people.

**Comment by Schneegans** [comment]
Yeah, I'll add a hint to the hint-label which shows tips in the bottom right corner.
