### ISSUE TITLE
No icon preview in menu editor for icons from ~/.local/share/icons

### ISSUE THREAD

**Issue by TomSaw** [Schneegans/Fly-Pie#248]
In Linux, icons stored in `/home/my_user/.local/share/icons` can be used by just typing the icons filename without the path nor mime-type extension.

I've got a `/home/my_user/.local/share/icons/sewing_machine.svg` f.e.

In flypies menu-editor **no icon is shown**:
![Screenshot from 2022-09-22 09-34-24](https://user-images.githubusercontent.com/738535/191686297-24ebff98-1581-4e6d-829b-9db63c7dfa53.png)

However, when using the menu the **icon appears**
![Screenshot from 2022-09-22 09-34-59](https://user-images.githubusercontent.com/738535/191686411-5dcb3f68-508f-4a7e-a61c-6d7ce7d54601.png)

## System
 - Fedora Workstation 36
 - Fly-Pie 17
 - GNOME 42.4

**Comment by Schneegans** [comment]
Thanks for the report! I'll look into this, I hope that this is pretty easy to fix :smile:

**Comment by Schneegans** [comment]
Ugh, it's a more complex thing. The issue is that the settings dialog uses GTK4 and the actual menu uses GTK3 for discovering icons. Both seem to behave differently here. While GTK3 also returns icons which are in the top-level directory of a icon search path (e.g. `.local/share/icons`), GTK4 seems to follow the [freedesktop specification](https://specifications.freedesktop.org/icon-theme-spec/latest/ar01s03.html) more strictly and only searches for icons in icon-theme sub-directories only.

This means, everything should work if you put your icon into this directory instead: `.local/share/icons/hicolor/scalable/actions`. Simply create it if it does not exist. With this, you extend the standard `hicolor` icon theme.

Does this work for you?

**Comment by TomSaw** [comment]
Wohaa... Works
Not an issue.
Thanks a lot!
