### ISSUE TITLE
Introduction should mention default keyboard shortcut

### ISSUE THREAD

**Issue by lightonflux** [Schneegans/Fly-Pie#303]
## The Motivation
I was surprised to learn that the possibility to open the menu with a keyboard shortcut was not mentioned in the introduction, nor was the default shortcut for the example menu. 

I assume many people want to test fly pie first without necessarily creating their own menu or checking the menu editor. The example menu is already very useful. So i think the introduction should mention and encourage the functionality to use the shortcut (and mention the option to change it e.g. to a special mouse key if possible).
 
## The Solution
Add a paragraph that talks about keyboard shortcuts. Or add an exercise to open the menu with the keyboard. 

I really like how the extension developed. The badges and exercises are fun and motivating. The editor is nice to look up.

**Comment by Schneegans** [comment]
That is a great idea. I'll do this for the next version!

**Comment by zeroheure** [comment]
I was coming to report the same thing!

The keyboard shortcut could be added in various places, because as a new user, I need to discover it easily :

- at the beginning of the extension description "_A marking menu which can be used to launch applications, simulate hotkeys ..._" could be re-writed as "_A marking menu. **Press  [shortcut here]** to launch applications, simulate hotkeys ..._"
- from the config window, in the About popup
- from the config window, in the parameters, possibly on the left of the Preview button
- at the very first part of the tutorial "_You can use Fly-Pie to launch applications etc. **(press [shortcut here]**. This interactive tutorial etc._"
