### ISSUE TITLE
Start of the names in bookmarked folders...

### ISSUE THREAD

**Issue by Rmano** [Schneegans/Fly-Pie#31]
## The Problem
When I use the "bookmarked folders" menu, there are anonymous folders shown. I know that if I hover over them I'll see the name in the central folder icon, but this is a bit slow (I change often the bookmarks, so I'll not learn by muscle memory where they are...)

## The Solution
Add a small text in the bookmarks with the first few letters of the name, like this:

![image](https://user-images.githubusercontent.com/6414907/96090689-e1d4cd80-0ec8-11eb-847e-57be7d8ce782.png)

## The Alternatives
I'll learn where they are ;-)

**Comment by Schneegans** [comment]
For Gnome-Pie, I added the option to show tiny labels on each item. Screenshot: https://1.bp.blogspot.com/-OYiJH_d753E/VhOaHwUH98I/AAAAAAAAW9I/k3pPoWciJ-I/s1600/gnome-pie.png

Maybe something like this could be done for Fly-Pie as well. This is a standard problem of pie menus; there is no good position for labels. I will think about it :smiley:

**Comment by Rmano** [comment]
That shot is nice ;-) although I think that the labels are needed just for the generic "folder" icons, because they are all the same...

**Comment by Philipp0205** [comment]
That would be awesome!

**Comment by Rmano** [comment]
Hi, is there any news on this? (I know, I shouldn't bump issues, but well, it's been a long time... please don't get angry at me!) 

Even the first few letters would be nice. The same applies to "recent documents" too...

**Comment by Schneegans** [comment]
I started working on this! Here are some initial images: https://ko-fi.com/post/Item-Labels-in-Fly-Pie-C0C8JM7A1

**Comment by BVengo** [comment]
Looks great! Is there any way to make it display the standard icons for folders such as Music, Photos, etc? Those basic icons could come with FlyPie like you already have for the rubbish and home folders.

To take it a bit further, bookmarks could also possibly have icon selections? My brief thoughts on implementation are:
- Add a config file mapping bookmark paths to icon path. This file initially contains only the basic bookmarks (home, downloads, music, photos...)
- New bookmarks have no mapping, so just look like the blank folder. Selecting a bookmark and changing the icon will add a new pair to the config file
- Removed bookmarks retain their config so that they can be easily re-added later
- An additional button opens up a list of all icon mappings (including old bookmarks) so that the user can remove old mappings they don't care about. Obviously this isn't necessary if you don't retain bookmark configs.

**Comment by Schneegans** [comment]
@BVengo: I added a fix which should make the bookmark items use the specific folder icons for the standard home directories (Documents, Music, etc). The alternative you're suggesting seems to be a bit complex, I think :smile:

**Comment by BVengo** [comment]
Fantastic! Thanks for the update :)
