### ISSUE TITLE
Mouse Button Support

### ISSUE THREAD

**Issue by Jak2k** [Schneegans/Fly-Pie#326]
## The Motivation
Easier selection for people with extra mouse keys.

## The Solution
A 3th or 4th mouse button can be set as shortcut. When keeping pressed, you can select stuff like you can with the left mouse key.

## The Alternatives
Using a key mapper. That would have the disadvantage, that you have to release the extra mouse key and then press down the left.

**Comment by Schneegans** [comment]
Hi there! Thanks for the suggestion but sadly binding something globally to mouse buttons is impossible on Wayland. However, as you said, there are some workarounds. I listed some ideas here: https://github.com/Schneegans/Fly-Pie/issues/221#issuecomment-1092088979

If you map the mouse button to something like <kbd>Ctrl</kbd> +<kbd>1</kbd>, you will not need to switch mouse buttons. The turbo-mode also works if a modifier button like <kbd>Ctrl</kbd> is pressed instead of the left mouse button!

**Comment by Jak2k** [comment]
It works, but for some reason its very laggy.
