### ISSUE TITLE
How to add comments to translatable Strings?

### ISSUE THREAD

**Issue by daPhipz** [Schneegans/Fly-Pie#62]
I am very sorry for being such a noob here, but I would love to help by improving the comments in the `.pot` file. Since it is generated automatically from `settings.ui` and other `.js` files, I wonder how I can add comments to translations.
For the `.js` files, it's easy - just add a `Translators` comment. But when I look at the `settings.ui` file, I don't really know what to do.

Yes, I see the `comment="foobar"`, but sometimes Strings are used more than once. Do I really have to edit the comment everywhere the String occurs in `settings.ui`? I get the feeling this file is generated automatically. If so, how can I add the comments?

Thanks in advance!

**Comment by Schneegans** [comment]
No need to apologize! The `ui` file is generated with glade (`sudo apt-get install glade`). Once you opened the file, here is what you need to do:

![grafik](https://user-images.githubusercontent.com/829942/102494044-60d6b580-4074-11eb-933e-6e243d1fc7d2.png)

I think it is sufficient to have the comment only in one place, but I actually never tried what happens if you have different commets for the same thing at different places...

I'll hopefully look into the PRs this evening!

**Comment by daPhipz** [comment]
Thank you very much!
Just after filing this issue, I saw that the file was created with glade. This program is not new to me, but I never noticed that button 😬

Thanks! I will have a look at the translation comments later this afternoon or tomorrow.
