### ISSUE TITLE
Calling submenus from the terminal

### ISSUE THREAD

**Issue by ghost** [Schneegans/Fly-Pie#95]
Hello there, I would like to call a submenu (a custom menu currently contained in another custom menu) using a command in my terminal. Exactly like what is currently possible through

```
gdbus call --session --dest org.gnome.Shell --object-path /org/gnome/shell/extensions/flypie \
             --method org.gnome.Shell.Extensions.flypie.ShowMenu 'MyMenu'
```

Is this a possibility? If so, how?

**Comment by Schneegans** [comment]
Just to make sure that I understood your request correctly: You want to open the complete menu but want a specific submenu to be selected already? So that it appears as if you clicked on it? This is not yet possible but should be quite easy to implement. For example, we could extend the `ShowMenu` method to accept a path to a submenu as second parameter. Or maybe the name of the submenu directly, but then the user has to make sure that the name is unique inside the menu.

As a workaround, you could copy the submenu in the menu editor to a new toplevel menu. This can be done by dragging the submenu to some empty space in the menu editor while holding down <kbd>Ctrl</kbd>. Then you can open this via the terminal.

**Comment by hThoreau** [comment]
You understood it perfectly.

> For example, we could extend the ShowMenu method to accept a path to a submenu as second parameter.

That would be perfect!

**Comment by Schneegans** [comment]
I will leave this opened until it's implemented. I will also drop a note here when I start working on it. So in the meantime - if anybody wants to implement this - it shouldn't be too hard!

**Comment by Schneegans** [comment]
Rescheduled to Fly-Pie 8, as Fly-Pie 7 will be focused on GNOME 40 support.

**Comment by Schneegans** [comment]
I am currently working on this in `feature/improve-dbus-api`...

**Comment by Schneegans** [comment]
This is now possible in the current `develop` branch. I chose to implement a `SelectItem()` D-Bus method as this seems to be more versatile. This is now also used by the live preview of the menu editor: If you click the preview button while you're inside a submenu, this submenu will be directly opened in the preview!

https://github.com/Schneegans/Fly-Pie/blob/develop/docs/dbus-interface.md#selecting-items-via-d-bus
